# Site settings
title: System-on-Chip Design & Verification
author:
  name: Nokuvimba Natalie Chiyaka
  email: G00423951@ATU.IE
description: "A blog."

# Build settings
remote_theme: jekyll/minima
